In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
ds=pd.read_csv("Wine.csv")
ds.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1

In [3]:
x=ds.iloc[:,:-1].values
y=ds.iloc[:,-1].values
print(x)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
print(x_train)

[[ 0.19127127 -1.32605234]
 [-0.83034359 -0.61397262]
 [-0.30394275 -1.17960831]
 [-0.5788387   1.13846573]
 [-0.68456232  1.07949933]
 [-0.37226604 -1.89329514]
 [ 1.65975788 -0.15086571]
 [-0.66932926  1.60264254]
 [-0.83315339  1.42102668]
 [-0.92789525  0.43300813]
 [-0.68282428 -0.05446736]
 [-0.42331923  1.40616251]
 [-0.93665141  2.15793092]
 [-0.95162315  1.64392103]
 [ 0.3526966  -0.95301198]
 [ 1.52902681  0.79463154]
 [ 1.5197322   0.38793643]
 [-0.78011534  0.80923332]
 [ 0.03120748 -1.44814549]
 [-0.98431101  0.78233127]
 [-0.79881822  0.85580383]
 [-0.82220673 -0.62251216]
 [ 1.35451169 -0.33745488]
 [-1.43944865 -0.6583275 ]
 [-0.01839675 -0.41767413]
 [-0.43926466  1.35702177]
 [ 1.5775648   0.33779656]
 [-0.44996734 -1.61617127]
 [ 1.25695337 -0.70593832]
 [-1.22097957  1.31243517]
 [-0.40082828 -1.28744934]
 [-0.10368141  1.30314749]
 [-0.92005092 -1.16333753]
 [-0.46706775  0.69396215]
 [ 1.71239395 -0.20852963]
 [ 1.59884     1.06006847]
 [ 1.38963286  0.81729096]
 

In [6]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
x_train=pca.fit_transform(x_train)
x_test=pca.transform(x_test)

In [7]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\user\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [17]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(lr.predict(x_test),y_test)
print(cm)
print(accuracy_score(lr.predict(x_test),y_test))

[[14  1  0]
 [ 0 12  1]
 [ 0  0  8]]
0.9444444444444444


In [9]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda=LDA(n_components=2)
x_train=lda.fit_transform(x_train,y_train)
x_test=lda.transform(x_test)

In [10]:
print(x_train)

[[ 0.45010322 -2.32999988]
 [-1.95398047 -1.0788082 ]
 [-0.7152439  -2.07268383]
 [-1.36213433  2.0003924 ]
 [-1.61092517  1.89678283]
 [-0.87602358 -3.32669936]
 [ 3.90577406 -0.26508538]
 [-1.57507845  2.81599513]
 [-1.96059253  2.49687882]
 [-2.18354088  0.7608364 ]
 [-1.60683518 -0.09570433]
 [-0.99616292  2.47076106]
 [-2.20414606  3.79168955]
 [-2.23937785  2.88852536]
 [ 0.8299724  -1.67453255]
 [ 3.59813521  1.39624307]
 [ 3.57626296  0.68164114]
 [-1.83578237  1.42189979]
 [ 0.07343805 -2.54452915]
 [-2.31629955  1.37463033]
 [-1.87979436  1.5037286 ]
 [-1.93483264 -1.09381297]
 [ 3.18746288 -0.59294027]
 [-3.38733816 -1.15674393]
 [-0.04329158 -0.73389311]
 [-1.03368603  2.38441612]
 [ 3.71235574  0.59354064]
 [-1.05887177 -2.83976639]
 [ 2.95788677 -1.24040067]
 [-2.87323255  2.30607323]
 [-0.9432368  -2.26217075]
 [-0.24398508  2.28975389]
 [-2.16508147 -2.04409451]
 [-1.09911279  1.2193574 ]
 [ 4.02963828 -0.36640635]
 [ 3.76242094  1.86264097]
 [ 3.27011068  1.43605782]
 

In [14]:
from sklearn.linear_model import LogisticRegression
lr1=LogisticRegression()
lr1.fit(x_train,y_train)

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\user\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [16]:
cm=confusion_matrix(lr1.predict(x_test),y_test)
print(cm)
print(accuracy_score(lr.predict(x_test),y_test))

[[14  1  0]
 [ 0 12  0]
 [ 0  0  9]]
0.9444444444444444
